dsccommunity/StorageDsc

DSCResources/MSFT_xDisk/MSFT_xDisk.psm1

If AllocationUnitSize is left out then it defaults to 0 which then caused the Test method to fail.

Fixed bug where AllocationUnitSize was not used

---

DSCResources/MSFT_xDisk/MSFT_xDisk.psm1
README.md

Fixed bug where DSC configuration fails on a machine where the disk is already initialised. The bug was due to not expanding the property BlockSize after the WMI query.

Fixed bug: Cannot compare "@{BlockSize=4096}" to "0"

---

DSCResources/MSFT_xDisk/MSFT_xDisk.psm1
README.md

The xDisk DSC Resource does not handle exceptions correctly. It
relied on `$($Error[0])` to display the error, but does not work
as the built in variable has not been populated yet with the exception.
We fixed this by capturing the Message property of the caught Exception
object and displaying that.
Fixes Issue #29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/30)

Fix Exception Handling in xDisk #29

---

DSCResources/MSFT_xDisk/MSFT_xDisk.psm1
tests/unit/MSFT_xDisk.tests.ps1

Get-WmiObject does not work on Nano Server (as of TP4), so Get/Test-TargetResource failed. Replaced it with Get-CimInstance which seems to work just as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/32)

MSFT_xDisk.psm1: Replaced Get-WmiObject with Get-CimInstance

---

README.md

Replaced instances of `xDiskImage` with `xStorage`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/40)

Corrected module name in readme

---

DSCResources/MSFT_xMountImage/MSFT_xMountImage.psm1
README.md

ObjectId is more verbose than DeviceId in Windows 10 Anniversary
Edition. In one instance, mounting a disk image and checking the
ObjectId returns
```
{1}\\WIN-56OJJQTNIEP\root/Microsoft/Windows/Storage/Providers_v2\WSP_Volume.ObjectId="{4c19525a-f384-11e4-8044-806e6f6e6963}:VO:\\?\Volume{b153fdb9-87e2-11e5-80b3-005056fce5a0}\"
```
The associated volume has a DeviceId of
```
\\?\Volume{b153fdb9-87e2-11e5-80b3-005056fce5a0}\
```
look for DeviceId in the ObjectId string instead of an exact match to
identify volumes. Fixes #48.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/49)

Fix identifying volume for Windows 10 Anniversary Edition

---

DSCResources/CommonResourceHelper.psm1
DSCResources/MSFT_xDisk/MSFT_xDisk.psm1
DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1
DSCResources/MSFT_xDiskAccessPath/en-us/MSFT_xDiskAccessPath.strings.psd1
DSCResources/MSFT_xMountImage/MSFT_xMountImage.psm1
DSCResources/MSFT_xWaitForDisk/MSFT_xWaitForDisk.psm1
DSCResources/MSFT_xWaitForVolume/MSFT_xWaitForVolume.psm1
DSCResources/StorageCommon/StorageCommon.psm1
Examples/Sample_InitializeDataDisk.ps1
Examples/Sample_InitializeDataDiskWithAccessPath.ps1
Examples/Sample_xMountImage_DismountISO.ps1
README.md
Tests/Integration/MSFT_xDisk.Integration.Tests.ps1
Tests/Integration/MSFT_xDiskAccessPath.Integration.Tests.ps1
Tests/Integration/MSFT_xMountImage_ISO.Integration.Tests.ps1
Tests/Integration/MSFT_xMountImage_VHD.Integration.Tests.ps1
Tests/Integration/MSFT_xWaitForDisk.Integration.Tests.ps1
Tests/Integration/MSFT_xWaitForVolume.Integration.Tests.ps1
Tests/TestHelpers/CommonTestHelper.psm1
Tests/Unit/MSFT_xDiskAssignPath.tests.ps1
Tests/Unit/MSFT_xMountImage.tests.ps1
Tests/Unit/MSFT_xWaitForDisk.tests.ps1
Tests/Unit/MSFT_xWaitForVolume.tests.ps1
Tests/Unit/StorageCommon.tests.ps1
tests/unit/MSFT_xDisk.tests.ps1

This PR:
- Fixes #66 
- Fixes #67
- Fixes #68 
These are some PSSA violations still in xDisk and xDiskAccessPath:
```
- MSFT_xDisk.psm1 (Line 96): File 'MSFT_xDisk.psm1' uses WMI cmdlet. For PowerShell 3.0 and above, use CIM cmdlet which perform the same tasks as the WMI cmdlets. The CIM cmdlets comply with WS-Management (WSMan) standards and with the Common Information Model (CIM) standard, which enables the cmdlets to use the same techniques to manage Windows computers and those running other operating systems.
- MSFT_xDisk.psm1 (Line 533): File 'MSFT_xDisk.psm1' uses WMI cmdlet. For PowerShell 3.0 and above, use CIM cmdlet which perform the same tasks as the WMI cmdlets. The CIM cmdlets comply with WS-Management (WSMan) standards and with the Common Information Model (CIM) standard, …
```

Fix xDiskAccessPath issue when reattaching volume - Fixes #66

---

CHANGELOG.md
Tests/Unit/MSFT_xDiskAccessPath.tests.ps1
appveyor.yml

Removed requirement on using Pester 3.4.6 because Pester bug fixed in 4.0.3.
Fixed unit tests for MSFT_xDiskAccessPath resource to be compatible with Pester 4.0.3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/83)

Fixed Unit tests and allowed Pester 4.0.3 usage - Fixes #76

---

CHANGELOG.md
Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1
Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1
Modules/xStorage/DSCResources/MSFT_xMountImage/MSFT_xMountImage.psm1
Modules/xStorage/DSCResources/MSFT_xWaitForDisk/MSFT_xWaitForDisk.psm1
Modules/xStorage/DSCResources/MSFT_xWaitForVolume/MSFT_xWaitForVolume.psm1
Modules/xStorage/xStorage.psd1
Tests/Integration/ModuleConflict.Tests.ps1

This resolves a high priority issue with newer versions of xNetworking, xCertificate, xStorage and xDFS conflicting with each other because the ResourceHelper cmdlets are being exported due to the way each resource imported them (using the PSD1 nested modules array).
This should be resolved in xNetworking, xStorage and xDFS as well to ensure no other conflicts.
This also contains a new integration test that will check for any further conflicts between resource modules. At some point it might be possible to move this test into the DSCResource.Tests common tests to provide more comprehensive conflict prevention. However, because the conflicts will potentially be between three different modules the number of modules compared will have to go in over time.
This fixes #93
---
This change …

Prevent ResourceHelper and Common cmdlets from being exported - Fixes #93

---

CHANGELOG.md
Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1
Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1

This is a minor fix to the error messages returned when a newly created partition does not become writable within 30 seconds. This was caused by the wrong Localization string label being specified.
This also removed two lines of code that were not actually required in the timeout.
- xDisk:
- Fix error message when new partition does not become writable before timeout.
- Removed unneeded timeout initialization code.
- xDiskAccessPath:
- Fix error message when new partition does not become writable before timeout.
- Removed unneeded timeout initialization code.
@Johlju - if you get a moment, would you mind reviewing? We really need some more reviewers so you can get a well deserved rest! :grin:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Fix Error Message Reported in xDisk & xDiskAccessPath if new partition does not become writable - Fixes #97

---

.vscode/settings.json
CHANGELOG.md

Added the VS Code PowerShell extension formatting settings that cause PowerShell files to be formatted as per the DSC Resource kit style guidelines. Fixes #100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/101)

Added .vscode\settings.json with default VS Code PowerShell extension formatting settings - Fixes #100

---

CHANGELOG.md
Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1
Modules/xStorage/DSCResources/MSFT_xMountImage/MSFT_xMountImage.psm1
Modules/xStorage/DSCResources/MSFT_xMountImage/en-us/MSFT_xMountImage.strings.psd1
Tests/Integration/MSFT_xDisk.Integration.Tests.ps1
Tests/Integration/MSFT_xDiskAccessPath.Integration.Tests.ps1
Tests/Integration/MSFT_xMountImage_ISO.Integration.Tests.ps1
Tests/Integration/MSFT_xMountImage_VHD.Integration.Tests.ps1
Tests/Integration/MSFT_xWaitForDisk.Integration.Tests.ps1
Tests/Integration/MSFT_xWaitForVolume.Integration.Tests.ps1
Tests/Integration/ModuleConflict.Tests.ps1
Tests/TestHelpers/CommonTestHelper.psm1
Tests/Unit/MSFT_xDiskAccessPath.Tests.ps1
Tests/Unit/MSFT_xMountImage.Tests.ps1
appveyor.yml

This PR primarily fixes #102.
However during investigation of #102, I found a way to enable the integration tests to run in AppVeyor by using DISKPART to create a new VHD. I decided to enable these to ensure that this module is being effectively tested on Windows Server 2012 R2.
This highlighted issue #105 as the integration tests failed on the AppVeyor build agent (but passed on Windows 10 and Windows Server 2016). I identified the cause of the problem and fixed it as well so that I could commit this fix.
The PR changes are as per:
- xDiskAccessPath:
- Fix error when used on Windows Server 2012 R2 - See [Issue 102](https://github.com/PowerShell/xStorage/issues/102).
- Removed requirement on Hyper-V PowerShell module to execute integration tests.
- xMountImage:
- Fix error when mounting …

Fix bug in xDiskAccessPath and xMountImage and enabled Integration Tests - Fixes #102, #105

---

CHANGELOG.md
Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1
Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.schema.mof
Modules/xStorage/DSCResources/MSFT_xDisk/en-us/MSFT_xDisk.strings.psd1
Tests/Integration/MSFT_xDisk.Integration.Tests.ps1
Tests/Integration/MSFT_xDisk.config.ps1
Tests/Unit/MSFT_xDisk.Tests.ps1

New parameters AllowDestructive and ClearDisk added. AllowDestructive indicates that potentially destructive changes (partition size change, file system format) are allowed to take place. AllowDestructive together with ClearDisk furthermore indicates that the target disk should be cleared of all data and OEM partitions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/90)

Partition resize and destructive switch implemented. Fixes #11, #50 and #89

---

.markdownlint.json
CHANGELOG.md
Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1
Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.schema.mof
Modules/xStorage/DSCResources/MSFT_xDisk/README.md
Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1
Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.schema.mof
Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/README.md
Modules/xStorage/DSCResources/MSFT_xWaitForDisk/MSFT_xWaitForDisk.psm1
Modules/xStorage/DSCResources/MSFT_xWaitForDisk/MSFT_xWaitForDisk.schema.mof
Modules/xStorage/DSCResources/MSFT_xWaitForDisk/README.md
Modules/xStorage/Modules/StorageDsc.Common/StorageDsc.Common.psm1
Modules/xStorage/xStorage.psd1
README.md
Tests/Integration/MSFT_xDisk.Integration.Tests.ps1
Tests/Integration/MSFT_xDiskAccessPath.Integration.Tests.ps1
Tests/Integration/MSFT_xMountImage_ISO.Integration.Tests.ps1
Tests/Integration/MSFT_xMountImage_VHD.Integration.Tests.ps1
Tests/Integration/MSFT_xWaitForDisk.Integration.Tests.ps1
Tests/Integration/MSFT_xWaitForVolume.Integration.Tests.ps1
Tests/TestHelpers/CommonTestHelper.psm1
Tests/Unit/MSFT_xDisk.Tests.ps1
Tests/Unit/MSFT_xDiskAccessPath.Tests.ps1
Tests/Unit/MSFT_xMountImage.Tests.ps1
Tests/Unit/MSFT_xWaitForDisk.Tests.ps1
Tests/Unit/MSFT_xWaitForVolume.Tests.ps1
Tests/Unit/StorageDsc.Common.Tests.ps1

This PR adds support for specifying the disk to work with using the Disk GUID. This is a unique value that is only assigned to the disk once it is initialized (a partition table is created). It will work with either MBR or GPT partition formats.
I've applied auto-formatting on any files I touched.
Tagging @Zuldan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/107)

Add support for DiskIdType Guid in xDisk, xDiskAccessPath and xWaitForDisk - Fixes #104

---

.vscode/settings.json
CHANGELOG.md
LICENSE
Modules/xStorage/xStorage.psd1

1. Updates License Year to 2017 and sets Company Name to Microsoft Corporation in LICENSE.MD and manifest.
1. Sets PowerShell Formatting preset to custom for VSCode.
Fixes #111 
Fixes #108 
**Task list:**
@Johlju - would you mind reviewing if you get a moment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/114)

Updated License Year and Set VSCode Custom Formatting present - Fixes #111

---

CHANGELOG.md
Tests/TestHarness.psm1

Prevents the unit tests in the DSCResource.Tests helper from being executed during test execution.
@Johlju - would you mind reviewing this when you get a moment. Should be pretty straight forward.
Fixes #118 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/119)

Prevent unit tests in DSCResource.Tests from running - Fixes #118

---

CHANGELOG.md
Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1
Modules/xStorage/DSCResources/MSFT_xDisk/en-us/MSFT_xDisk.strings.psd1
Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1
Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/en-us/MSFT_xDiskAccessPath.strings.psd1
Modules/xStorage/Modules/StorageDsc.Common/StorageDsc.Common.psm1
Tests/Integration/MSFT_xDisk.Integration.Tests.ps1
Tests/Integration/MSFT_xDiskAccessPath.Integration.Tests.ps1
Tests/Unit/MSFT_xDisk.Tests.ps1
Tests/Unit/MSFT_xDiskAccessPath.Tests.ps1
Tests/Unit/StorageDsc.Common.Tests.ps1

This PR fixes the issue in xDisk and xDiskAccessPath that occurs when the Size parameter is not specified, but the partition on the disk already exists but is not assigned to a Drive Letter or an Access Path.
This also improves the integration test layout by adding contexts to group the tests.
- Fixes #103 
**Task list:**
@johlju - another one for you sir if you get time -no rush! :grin: I applied autoformatting to the files as well, which did correct some of the lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/130)

Fix when max size used and disk partitioned and formatted but not mounted - Fixes #103

---

CHANGELOG.md

This PR is to correct the CHANGELOG.MD entry for a previous PR #133.
The entry got put into the released (3.4.0.0) section instead of the UNRELEASED section.
- #135
**Task list:**
@Johlju - would you mind reviewing this? It is just a minor correction to a previous PR I merged (it was looked to be easier to fix in a separate PR).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/136)

Moved entry for new xOpticalDiskDriveLetter resource into Unreleased section - Fixes #135

---

CHANGELOG.md
DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1
DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.schema.mof
DSCResources/MSFT_DiskAccessPath/en-us/MSFT_DiskAccessPath.strings.psd1
Tests/Integration/MSFT_DiskAccessPath.Integration.Tests.ps1
Tests/Unit/MSFT_DiskAccessPath.Tests.ps1

- DiskAccessPath
Update the resource to not assign a drive letter by default when adding
a disk access path. Adding a Set-Partition -NoDefaultDriveLetter $NoDefaultDriveLetter block
defaulting to true. When adding access paths the disks will no longer have
drive letters automatically assigned on next reboot which is the desired
behavior.
- Fixes [Issue #145](https://github.com/PowerShell/StorageDsc/issues/145).
- [x ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
- [x ] Resource parameter descriptions added/updated in schema.mof
- [x ] Comment-based help added/updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

diskaccesspath: fixes issue 145 drive letter assignment to mountpoint volumes

---

CHANGELOG.md
Tests/Unit/MSFT_DiskAccessPath.Tests.ps1

This PR corrects the unit tests for DiskAccessPath to meet current standards and ensure -Exactly is included in all Assert-MockCalled checks.
- Fixed #199
@johlju - would you mind reviewing this one?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/storagedsc/201)

Clean up unit tests for DiskAccessPath - Fixes #199

---

CHANGELOG.md
DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1
Tests/Unit/MSFT_DiskAccessPath.Tests.ps1

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/storagedsc/198)

Disk-AccessPath: fixing get-partition to pull current state of object

---

CHANGELOG.md
DSCResources/MSFTDSC_Disk/MSFTDSC_Disk.psm1
DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1
DSCResources/MSFT_DiskAccessPath/en-US/MSFT_DiskAccessPath.strings.psd1
DSCResources/MSFT_MountImage/MSFT_MountImage.psm1
DSCResources/MSFT_WaitForDisk/MSFT_WaitForDisk.psm1
DSCResources/MSFT_WaitForVolume/MSFT_WaitForVolume.psm1
Modules/StorageDsc.Common/StorageDsc.Common.psm1
Tests/Unit/MSFT_DiskAccessPath.Tests.ps1

- DiskAccessPath:
- Added function to force refresh of disk subsystem at the start of
Set-TargetResource to prevent errors occuring when the disk access
path is already assigned - See [Issue 121](https://github.com/PowerShell/StorageDsc/issues/121)
This PR also supercedes #152, #126 
- Fixes #121 
@johlju - would you mind reviewing this when you get a chance?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/storagedsc/209)

DiskAccessPath Add Disk Subsystem Refresh before set - Fixes #121

---

CHANGELOG.md
DSCResources/MSFTDSC_Disk/MSFTDSC_Disk.psm1
DSCResources/MSFTDSC_Disk/README.md
DSCResources/MSFT_DiskAccessPath/README.md
DSCResources/MSFT_WaitForDisk/README.md
Tests/Integration/MSFTDSC_Disk.Integration.Tests.ps1
Tests/Unit/MSFTDSC_Disk.Tests.ps1

This PR introduces a workaround that fixes issue #181 where the reported maximum supported size of a partition would be approximately 1MB bigger than the actual size of the partition. As long as it is unclear why the New-Partition and Get-PartitionSupportedSize cmdlets report different data if neither Offset nor Alignment parameters are used, this workaround should remain in place.
If this is not the case, Test-TargetResource for a disk configured to use the remaining size will always return false and trigger an endless cycle of LCM runs.
This PR replaces #197.
- Fixes #181 
@johlju - would you mind reviewing when you have a moment?
---
This change is [<img …

Disk: Fix Partition MaxSize discrepency - Fixes #181

---

CHANGELOG.md
DSCResources/MSFT_MountImage/MSFT_MountImage.psm1
DSCResources/MSFT_OpticalDiskDriveLetter/MSFT_OpticalDiskDriveLetter.psm1

Correct Hashtable Style.
- Fixes #219
@johlju - would you mind reviewing for me?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/storagedsc/220)

Fix hashtable format - Fixes #219

---

CHANGELOG.md
source/DSCResources/DSC_OpticalDiskDriveLetter/DSC_OpticalDiskDriveLetter.psm1
source/DSCResources/DSC_OpticalDiskDriveLetter/en-US/DSC_OpticalDiskDriveLetter.strings.psd1
tests/Integration/DSC_OpticalDiskDriveLetter.Integration.Tests.ps1
tests/Unit/DSC_OpticalDiskDriveLetter.Tests.ps1

Suppress exception when requested optical disk drive does not exist and Ensure is set to `Absent`
- Fixes #194
@johlju  - can you review for me when you get time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/storagedsc/235)

OpticalDiskDriveLetter: Suppress No Drive Exception - Fixes #194

---

CHANGELOG.md
source/DSCResources/DSC_Disk/DSC_Disk.psm1
tests/Unit/DSC_Disk.Tests.ps1

- Fix bug when multiple partitions with the same drive letter are
reported by the disk subsystem - Fixes [Issue #210](https://github.com/dsccommunity/StorageDsc/issues/210).
- Fixes #210 
@johlju - would you mind reviewing this one for me?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/storagedsc/243)

Disk: Fix bug when Partition reported twice - Fixes #210

---

CHANGELOG.md
source/StorageDsc.psd1

This PR removes the whitespace between the 'Dev Drive'  tag in the psd1 file. This should allow the deployment to pass. Thats my bad for doing a find and replace in the previous PR. 
- Fixes #280 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/StorageDsc/281)

Remove space between 'Dev Drive' tag  in psd1 file so deployment passes

---

CHANGELOG.md
source/DSCResources/DSC_Disk/README.md

@johlju - this is a BREAKING CHANGE commit. I'm going to squash merge this into a new commit anyway (with BREAKING CHANGE) to trigger the major version bump.
Administrative PR to force major version bump.,
- Fixes @282
@johlju - would you mind reviewing when you have time?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/StorageDsc/283)

Trigger BREAKING CHANGE major release - Fixes #282

---

.vscode/analyzersettings.psd1
.vscode/settings.json
CHANGELOG.md
GitVersion.yml
RequiredModules.psd1
Resolve-Dependency.ps1
Resolve-Dependency.psd1
azure-pipelines.yml
build.ps1
build.yaml
source/DSCResources/DSC_OpticalDiskDriveLetter/DSC_OpticalDiskDriveLetter.psm1
source/DSCResources/DSC_OpticalDiskDriveLetter/README.md
source/DSCResources/DSC_OpticalDiskDriveLetter/en-US/DSC_OpticalDiskDriveLetter.strings.psd1
source/Examples/README.md
tests/Unit/DSC_OpticalDiskDriveLetter.Tests.ps1

This PR prevents an exception from occurring for some ODDs when the device is not mounted, but
appears with a DriveLetter as 'cdRom0' or some other value that is not a volume{guid} pattern.
Instead, a warning is reported and the device is reported as unmanageable.
This also updates the pipeline files to latest DSC community pattern and sampler tasks.
 
- Fixes #289 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/StorageDsc/290)

OpticalDiskDrive prevent exception on unmanageable device condition - Fixes #289

---

CHANGELOG.md
source/Examples/Resources/Disk/2-Disk_InitializeDataDiskUsingUniqueId.ps1
source/Examples/Resources/WaitForDisk/1-WaitForDisk_InitializeDataDisk.ps1

Updated AllocationUnitSize in examples to be a valid UInt32 value instead of a String.
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/StorageDsc/293)

Disk: AllocationUnitSize in examples should be UInt32 and not String
