dsccommunity/StorageDsc

README.md

Fixed documentation (changed parameter name Count to RetryCount in xWaitForDisk resource). Fixes #8

---

DSCResources/MSFT_xDisk/MSFT_xDisk.psm1
README.md
appveyor.yml
xStorage.psd1

Release of version 2.4.0.0 of xStorage

---

README.md
tests/unit/MSFT_xDisk.tests.ps1

Updated unit tests to include both branches of If to test for both unformatted and formatted volumes

Updated unit Tests, Fixes for #24 and #25

---

DSCResources/MSFT_xDisk/MSFT_xDisk.psm1
README.md
appveyor.yml
tests/unit/MSFT_xDisk.tests.ps1
xStorage.psd1

Releasing version 2.6.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/36)

Release of version 2.6.0.0 of xStorage

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/72)

Fixed copy/paste error in README

---

DSCResources/CommonResourceHelper.psm1
DSCResources/MSFT_xDisk/MSFT_xDisk.psm1
DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1
DSCResources/MSFT_xDiskAccessPath/en-us/MSFT_xDiskAccessPath.strings.psd1
DSCResources/MSFT_xMountImage/MSFT_xMountImage.psm1
DSCResources/MSFT_xWaitForDisk/MSFT_xWaitForDisk.psm1
DSCResources/MSFT_xWaitForVolume/MSFT_xWaitForVolume.psm1
DSCResources/StorageCommon/StorageCommon.psm1
Examples/Sample_InitializeDataDisk.ps1
Examples/Sample_InitializeDataDiskWithAccessPath.ps1
Examples/Sample_xMountImage_DismountISO.ps1
README.md
Tests/Integration/MSFT_xDisk.Integration.Tests.ps1
Tests/Integration/MSFT_xDiskAccessPath.Integration.Tests.ps1
Tests/Integration/MSFT_xMountImage_ISO.Integration.Tests.ps1
Tests/Integration/MSFT_xMountImage_VHD.Integration.Tests.ps1
Tests/Integration/MSFT_xWaitForDisk.Integration.Tests.ps1
Tests/Integration/MSFT_xWaitForVolume.Integration.Tests.ps1
Tests/TestHelpers/CommonTestHelper.psm1
Tests/Unit/MSFT_xDiskAssignPath.tests.ps1
Tests/Unit/MSFT_xMountImage.tests.ps1
Tests/Unit/MSFT_xWaitForDisk.tests.ps1
Tests/Unit/MSFT_xWaitForVolume.tests.ps1
Tests/Unit/StorageCommon.tests.ps1
appveyor.yml
tests/unit/MSFT_xDisk.tests.ps1
xStorage.psd1

Releasing version 2.9.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/74)

Release of version 2.9.0.0 of xStorage

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

Copied from xFailOverCluster with adjustments to resource name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/113)

Added .github support files - Fixes #112

---

CHANGELOG.md
README.md

Added Documentation and Examples section to README.MD. Wording mostly copied from SharePointDsc.
Fixes #116
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/117)

Added Documentation and Examples section to README.MD - Fixes #116

---

.MetaTestOptIn.json
CHANGELOG.md
Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.psm1
Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1
Modules/xStorage/Modules/StorageDsc.Common/StorageDsc.Common.psm1
Modules/xStorage/Modules/StorageDsc.ResourceHelper/StorageDsc.ResourceHelper.psm1

This PR corrects the BOM on several of the module files and opts into the common module and script validation tests.
- Fixes #115
**Task list:**
@Johlju - this one should be a trivial review. Hope you don't mind - no rush!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/124)

Correct BOM on Module Files - Fixes #115

---

CHANGELOG.md
Tests/Integration/MSFT_xDisk.Integration.Tests.ps1
Tests/Integration/MSFT_xDiskAccessPath.Integration.Tests.ps1
Tests/Integration/MSFT_xMountImage_ISO.Integration.Tests.ps1
Tests/Integration/MSFT_xMountImage_VHD.Integration.Tests.ps1
Tests/Integration/MSFT_xWaitForDisk.Integration.Tests.ps1
Tests/Integration/MSFT_xWaitForVolume.Integration.Tests.ps1
Tests/Integration/ModuleConflict.Tests.ps1
Tests/Unit/MSFT_xDisk.Tests.ps1
Tests/Unit/MSFT_xDiskAccessPath.Tests.ps1
Tests/Unit/MSFT_xMountImage.Tests.ps1
Tests/Unit/MSFT_xWaitForDisk.Tests.ps1
Tests/Unit/MSFT_xWaitForVolume.Tests.ps1
Tests/Unit/StorageDsc.Common.Tests.ps1

Update all tests to support Pester V4 standard.
Fixes #120
**Task list:**
@Johlju - I have another one for you :grin: hopefully this one is easy as all I've done is update the pester tests to V4 using the script you pointed me to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xstorage/125)

Converted Pester tests to V4 - Fixes #120

---

CHANGELOG.md
Modules/StorageDsc/DSCResources/MSFTDSC_Disk/README.md

This PR Documents the Disk known issue when the 'defragsvc' is started.
I didn't add tests because in my experimentation, this issue does not always 100% happen (it seems to depend on the disk and whether the service is doing work at the time).
- Fixes #172
@johlju - would you mind reviewing when you get a chance?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/storagedsc/173)

Added 'defragsvc' service conflict known issue to README.MD for Disk - Fixes #172

---

CHANGELOG.md
Modules/StorageDsc/Modules/StorageDsc.Common/StorageDsc.Common.psm1
Modules/StorageDsc/Modules/StorageDsc.ResourceHelper/StorageDsc.ResourceHelper.psm1

This PR fixes the minor style violations in the support modules.
- Fixes #153 
@johlju - would you mind reviewing? Just a minor style clean up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/storagedsc/174)

Correct style violations in support modules - Fixes #153

---

CHANGELOG.md
Modules/StorageDsc/DSCResources/MSFT_WaitForDisk/MSFT_WaitForDisk.psm1
Modules/StorageDsc/DSCResources/MSFT_WaitForDisk/MSFT_WaitForDisk.schema.mof
Tests/Integration/MSFT_WaitForDisk.Integration.Tests.ps1
Tests/Unit/MSFT_WaitForDisk.Tests.ps1

This adds a new read only property to the WaitForDisk Resource, which can be shown in `Get-TargetResource`. The returnvalue is evaluated by calling the `Test-TargetResource` Method
- Fixes #158 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/storagedsc/175)

WaitForDisk: adding isAvailable property

---

CHANGELOG.md
StorageDsc.psd1

This PR corrects the module manifest to adopt DSC Resource kit standards for Copyright, Author and Company.
Added 'DscResourcesToExport' to manifest to improve information in
PowerShell Gallery and removed wildcards from 'FunctionsToExport',
'CmdletsToExport', 'VariablesToExport' and 'AliasesToExport
- Fixes #191 
- Fixes #192
@johlju - would you mind reviewing for me when you have a chance - just a simple Manifest cleanup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/storagedsc/193)

Clean up Module Manifest - Fixes #191

---

CHANGELOG.md
appveyor.yml

This PR fixes the example publish to PS Gallery by adding the missing environment variable to 
- Fixes #202
@johlju - would you mind reviewing? Should be a quick one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/storagedsc/203)

Added Gallery_Api Environment variable to AppVeyor - Fixes #202

---

CHANGELOG.md
DSCResources/MSFTDSC_Disk/MSFTDSC_Disk.psm1
DSCResources/MSFT_OpticalDiskDriveLetter/README.md
StorageDsc.psd1
Tests/Unit/MSFTDSC_Disk.Tests.ps1

Releasing version 4.7.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/storagedsc/207)

Release of version 4.7.0.0 of StorageDsc

---

CHANGELOG.md
Examples/Resources/Disk/1-Disk_InitializeDataDisk.ps1

Fixes #214 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/storagedsc/218)

Updated disk example with size in bytes without measurement unit

---

CHANGELOG.md
README.md

This PR updates the build badges with the correct ID of the pipeline.
@johlju - would you mind reviewing for me?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/storagedsc/229)

Fix build badges

---

CHANGELOG.md
build.yaml
source/WikiSource/Home.md

Automate publishing of Wiki content.
- Fixes #241 
@johlju - could you review when you have a moment?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/storagedsc/242)

Automate Wiki Publish - Issue #241

---

CHANGELOG.md
source/Examples/Resources/MountImage/1-MountImage_DismountISO.ps1

This PR corrects the example `1-MountImage_DismountISO.ps1`.
- Fixes #221 
@johlju - would you mind reviewing for me when you have time? I'm starting to get a bit more time again, so I'm getting back into DSC. :grin:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/storagedsc/249)

Correct Example MountImage Dismount - Fixes #221

---

CHANGELOG.md
GitVersion.yml
README.md
azure-pipelines.yml
build.yaml
source/Examples/Resources/Disk/1-Disk_InitializeDataDisk.ps1
source/Examples/Resources/Disk/2-Disk_InitializeDataDiskUsingUniqueId.ps1
source/Examples/Resources/DiskAccessPath/1-DiskAccessPath_InitializeDataDiskWithAccessPath.ps1
source/Examples/Resources/DiskAccessPath/2-DiskAccessPath_InitializeDataDiskWithAccessPathUsingUniqueId.ps1
source/Examples/Resources/MountImage/1-MountImage_DismountISO.ps1
source/Examples/Resources/MountImage/2-MountImage_MountISO.ps1
source/Examples/Resources/MountImage/3-MountImage_MountVHD.ps1
source/Examples/Resources/OpticalDiskDriveLetter/1-OpticalDiskDriveLetter_SetDriveLetter.ps1
source/Examples/Resources/OpticalDiskDriveLetter/2-OpticalDiskDriveLetter_RemoveDriveLetter.ps1
source/Examples/Resources/WaitForDisk/1-WaitForDisk_InitializeDataDisk.ps1
source/Examples/Resources/WaitForDisk/3-WaitForDisk_InitializeDataDiskWithAccessPathUsingUniqueId.ps1
source/Examples/Resources/WaitForVolume/1-WaitForVolume_VHD.ps1
source/Examples/Resources/WaitForVolume/2-WaitForVolume_ISO.ps1
source/StorageDsc.psd1
source/WikiSource/Home.md

This PR is the first stage of renaming the `master` branch to `main`.
- Fixes #250 
@johlju - would you mind reviewing this when you get time? Should be simple one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/storagedsc/251)

Updated pipeline files to support change of master to main - Fixes #250

---

CHANGELOG.md
GitVersion.yml

This PR updates the `GitVersion.yml` to the latest pattern.
- Fixes #252
@johlju - would you mind reviewing when you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/storagedsc/253)

Update Gitversion to latest pattern - Fixes #252

---

CHANGELOG.md
README.md
RequiredModules.psd1
azure-pipelines.yml
build.yaml
codecov.yml

This PR adds build coverage reporting to build pipeline. It also updates the build to use Sampler.GitHubTasks.
- Fixes #255 
- Fixes #254 
@johlju - would you mind reviewing when you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/storagedsc/256)

Add Code Coverage Reporting to Build Pipeline - Fixes #255

---

CHANGELOG.md
README.md
azure-pipelines.yml

This PR updates the pipeline to use the *pipeline tasks.
@johlju - could you review when you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/storagedsc/257)

Updated pipeline tasks to latest version

---

CHANGELOG.md
azure-pipelines.yml
source/DSCResources/DSC_OpticalDiskDriveLetter/DSC_OpticalDiskDriveLetter.psm1
source/DSCResources/DSC_OpticalDiskDriveLetter/README.md
source/DSCResources/DSC_OpticalDiskDriveLetter/en-US/DSC_OpticalDiskDriveLetter.strings.psd1
tests/Integration/DSC_OpticalDiskDriveLetter.Integration.Tests.ps1
tests/Unit/DSC_Disk.Tests.ps1
tests/Unit/DSC_OpticalDiskDriveLetter.Tests.ps1

This PR fixes #285 by reworking the method of detecting whether an optical disk drive can be managed by this resource. The previous method of detection was unreliable. The new method of detection is described in the README.md:
This resource is intended to manage _permanent_ optical disk drives that are
either physically present in the system or are presented to the system by
hypervisors or other virtualization platforms. It is not intended to be used
to manage _temporary_ optical disk drives that are created when mounting ISOs
on Windows Server 2012 and newer. Mounted ISO drives should be managed by the
`DSC_MountImage` resource.
To detect whether a drive is a mounted ISO the following logic is used.
For a CIM instance of a `cimv2:Win32_CDROMDrive` class representing an
optical disk …

OpticalDiskDriveLetter : Rework detection method for mounted ISO - Fixes #285

---

CHANGELOG.md
azure-pipelines.yml
build.yaml

This PR fixes the CI pipeline errors caused by prefix.ps1/suffix.ps1 not being present (not needed). Also updates the markdown generation. Also added testing on Windows Server 2025. Also converted CI pipeline to use matrix for Unit tests and Integration tests.
- Fixes #294 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/StorageDsc/295)

Update: CI pipeline to fix Markdown Generation warning and prefix/suffix errors - Fixes #294

---

CHANGELOG.md
azure-pipelines.yml
build.yaml

Move integration tests to own stage.
Add merge CodeCoverage task.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/StorageDsc/297)

Update pipeline used in NetworkingDsc
